baseurl = "/"
languageCode = "en-us"
title = "afrandsen | R, Bikes and Training"
theme = "hugo-xmin"
googleAnalytics = "UA-145443946-1"
disqusShortname = "afrandsen"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    blog = "/blog/:year/:month/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3     
[[menu.main]]
    name = "License"
    url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Andreas Frandsen's Personal Website."
    footer = "[&copy; Andreas Frandsen 2019](https://afrandsen.rbind.io)"
    github = "https://github.com/afrandsen"
    linkedin = "https://www.linkedin.com/in/andreas-kracht-frandsen-09438315a"
    strava = "https://www.strava.com/athletes/andreas_frandsen"
    GithubEdit = "https://github.com/afrandsen/afrandsen/edit/master/content/"