---
title: Transformed Exponentially Smoothed Power and Other Techniques
author: Andreas Frandsen
date: '2019-08-17'
slug: transformed-exponentially-smoothed-power-and-other-techniques
categories: []
lastmod: 0
tags:
  - R
  - Training
  - Power
  - Power meter
  - Watt
  - Smoothing
  - TDF
  - Lactate
  - LT
  - Threshold
  - Heartrate
  - AU
  - Aarhus University
  - Statistics
description: "A statistic breakdown of the different components regarding normalization of power. A blog post by afrandsen."
bibliography: C:/Users/AKF/Documents/afrandsen/references/transformed-exponentially-smoothed-power-and-other-techniques/references.bib
nocite: '@*'
link-citations: true
---



<p>A lot have been said regarding smoothing and transformation of exerted power. Different terms have been used by physiologists, without a proper explanation of the statistical aspects behind their metrics. The time has come to take the no bullshit approach towards this topic. Thus this article seeks to explain openly the how and why of these metrics. And finally provide a more robust model, in terms of unbiasedness.</p>
<div id="pseudo-stochasticity-of-power" class="section level1">
<h1>Pseudo-Stochasticity of Power</h1>
</div>
<div id="existing-metrics" class="section level1">
<h1>Existing Metrics</h1>
<p>Andrew Coggan, Philip Skiba and Strava has each provided their own metrics regarding smoothing and transformation of power. I will refer to these as Coggan Power, Skiba Power and Strava Power, you can check out the correct metric names yourself.</p>
<div id="coggan-power" class="section level2">
<h2>Coggan Power</h2>
<p>Developed by Andrew R. Coggan. Also known as IsoPower in GoldenCheetah. Explained in <span class="citation">(Allen and Coggan <a href="#ref-Coggan2012" role="doc-biblioref">2012</a>)</span>.</p>
<div id="technique" class="section level3">
<h3>Technique</h3>
<p>Calculate simple 30 s moving average. Take fourth power. Take mean. Take fourth root.</p>
</div>
<div id="issues" class="section level3">
<h3>Issues</h3>
<p>Biased towards the last</p>
<p><span class="math display">\[\Delta = x - 30\]</span></p>
<p>seconds of the ride/interval, where <span class="math inline">\(x\)</span> is the full ride/interval in seconds.</p>
</div>
</div>
<div id="skiba-power" class="section level2">
<h2>Skiba Power</h2>
<p>Developed by Philip F. Skiba. Explained in <span class="citation">(Skiba <a href="#ref-Skiba2008" role="doc-biblioref">2008</a>)</span>.</p>
<div id="technique-1" class="section level3">
<h3>Technique</h3>
<p>Calculate 25 s exponential moving average. Take fourth power. Take mean. Take fourth root.</p>
</div>
</div>
</div>
<div id="issues-1" class="section level1">
<h1>Issues</h1>
<p>Biased towards 0.</p>
<div id="strava-power" class="section level2">
<h2>Strava Power</h2>
<p>Developed by Strava, seems to be equivalent to Skiba Power. Somewhat explained in <span class="citation">(“Power Analysis Features for Summit” <a href="#ref-Strava" role="doc-biblioref">n.d.</a>)</span>.</p>
<div id="technique-2" class="section level3">
<h3>Technique</h3>
<p>See Skiba Power.</p>
</div>
<div id="issues-2" class="section level3">
<h3>Issues</h3>
<p>See Skiba Power.</p>
</div>
</div>
</div>
<div id="relation-between-power-and-lactate" class="section level1">
<h1>Relation Between Power and Lactate</h1>
<p>To find how the body’s physiological response is to exercise intensity, we will look at how lactate acid levels in the blood increases with intensity. We expect that the lactate acid level is an increasing function of exercise intensity, but is it a linear function? Let’s try to visualize it first.</p>
<p>We will take look at a very small data sample taking from my body some years ago, originally it was performed to measure my lactate threshold.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div class="figure" style="text-align: center"><span id="fig:lactate-power"></span>
<img src="/blog/2019-08-17-transformed-exponentially-smoothed-power-and-other-techniques_files/figure-html/lactate-power-1.svg" alt="Exponential curvature is observed." width="336" />
<p class="caption">
Figure 1: Exponential curvature is observed.
</p>
</div>
<p>Given the fact that I haven’t transformed the axes, we observe that the relationship is nonlinear. This fits well with the theory that the body can’t keep up with lactate acid being produced at high levels of effort as observed in <span class="citation">(Faude, Kindermann, and Meyer <a href="#ref-Faude2009" role="doc-biblioref">2009</a>)</span>. Thus it accumulates very fast in the body at high intensities. We also observe that the relation is exponential or curvilinear. So let’s try to fit an (natural) exponential model to the data, of the form</p>
<p><span class="math display">\[f(x)=\alpha \mathrm{e}^{\beta x},\]</span></p>
<p>where <span class="math inline">\(x\in\mathbb{R}^+\)</span>. Let us at the same time try to fit another exponential model, of the form</p>
<p><span class="math display">\[f(x)=\alpha x^{\beta},\]</span></p>
<p>which I (misleadingly) will refer to as a power model, where <span class="math inline">\(x\in\mathbb{R}^+\)</span>. We will have to set some initial parameters (this is essentially a very hard part). Next up: code! Scroll down to see the results.</p>
<pre class="r"><code># Fit Exponential model
model.1 &lt;- nls(formula = lactate ~ a * exp(b*watt),
             start = list(a=0.222, b=0.01))
# Fit Power model
model.2 &lt;- nls(formula = lactate ~ a*watt^b,
               start = list(a=0.000001, b=2.3))

models &lt;- tibble(model.1, model.2)

RMSE &lt;- function(model){
  sqrt(mean((predict(model)-lactate)^2))
}

# Statistical summary of Exponential model
summary(model.1)</code></pre>
<pre><code>## 
## Formula: lactate ~ a * exp(b * watt)
## 
## Parameters:
##   Estimate Std. Error t value Pr(&gt;|t|)   
## a 0.156876   0.055956   2.804  0.06765 . 
## b 0.012003   0.001405   8.545  0.00337 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2509 on 3 degrees of freedom
## 
## Number of iterations to convergence: 3 
## Achieved convergence tolerance: 4.202e-06</code></pre>
<pre class="r"><code># Statistical summary of Power model
summary(model.2)</code></pre>
<pre><code>## 
## Formula: lactate ~ a * watt^b
## 
## Parameters:
##    Estimate Std. Error t value Pr(&gt;|t|)   
## a 7.540e-07  1.843e-06   0.409  0.70992   
## b 2.765e+00  4.425e-01   6.248  0.00827 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3314 on 3 degrees of freedom
## 
## Number of iterations to convergence: 8 
## Achieved convergence tolerance: 5.116e-06</code></pre>
<pre class="r"><code># Calculate RMSE for both models
map_dbl(models, RMSE)</code></pre>
<pre><code>##   model.1   model.2 
## 0.1943845 0.2566714</code></pre>
<p>We achieve the following equation for the exponential model</p>
<p><span class="math display">\[f(x)=0.156875\cdot \mathrm{e}^{0.012003 x},\]</span></p>
<p>with an <a href="https://en.wikipedia.org/wiki/Root-mean-square_deviation">RMSE</a> of 0.1944 and a <a href="https://en.wikipedia.org/wiki/Standard_error">SE</a> of 0.2509.</p>
<p>The power model has this equation</p>
<p><span class="math display">\[f(x)=0.000000754\cdot x^{2.765},\]</span></p>
<p>with an RMSE of 0.2567 and a SE of 0.3314. Let’s visualize it.</p>
<div class="figure" style="text-align: center"><span id="fig:lactate-power-fit"></span>
<img src="/blog/2019-08-17-transformed-exponentially-smoothed-power-and-other-techniques_files/figure-html/lactate-power-fit-1.svg" alt="Exponential model provides best fit." width="336" />
<p class="caption">
Figure 2: Exponential model provides best fit.
</p>
</div>
</div>
<div id="half-life-of-heartrate" class="section level1">
<h1>Half-Life of Heartrate</h1>
</div>
<div id="statistical-averages" class="section level1">
<h1>Statistical Averages</h1>
<p>A great amount of statistical averages exists when one wants to examine data. Some of these methods are as of today used in examining data from power meters.</p>
<p>Down below I will provide the some of the various formulas including negatives related to each method.</p>
<div id="arithmetic-average" class="section level2">
<h2>Arithmetic Average</h2>
<p>Is calculated as</p>
<p><span class="math display">\[\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i,\]</span></p>
<p>where <span class="math inline">\(i=1,\dots,n\)</span>.</p>
</div>
<div id="median" class="section level2">
<h2>Median</h2>
</div>
<div id="simple-moving-average" class="section level2">
<h2>Simple Moving Average</h2>
<p><span class="math display">\[\bar{x}_\text{SMA} = \frac{1}{n} \sum x_i \]</span></p>
</div>
<div id="weighted-moving-average" class="section level2">
<h2>Weighted Moving Average</h2>
</div>
<div id="exponential-moving-average" class="section level2">
<h2>Exponential Moving Average</h2>
<p>Is calculated as</p>
<p><span class="math display">\[\begin{align} s_0 &amp;= x_0\\ s_t &amp;= \alpha s_t+(1-\alpha)s_{t-1},\end{align}\]</span></p>
<p>where <span class="math inline">\(t=1,\dots,n\)</span>.</p>
</div>
<div id="unbiased-exponential-moving-average" class="section level2">
<h2>Unbiased Exponential Moving Average</h2>
<div id="normalization-factor" class="section level3">
<h3>Normalization Factor</h3>
<div class="figure" style="text-align: center"><span id="fig:scale"></span>
<img src="/blog/2019-08-17-transformed-exponentially-smoothed-power-and-other-techniques_files/figure-html/scale-1.svg" alt="The scaling factor converges towards 100 %." width="336" />
<p class="caption">
Figure 3: The scaling factor converges towards 100 %.
</p>
</div>
<p><img src="/blog/2019-08-17-transformed-exponentially-smoothed-power-and-other-techniques_files/figure-html/smoothing-1.svg" width="393.6" /><img src="/blog/2019-08-17-transformed-exponentially-smoothed-power-and-other-techniques_files/figure-html/smoothing-2.svg" width="393.6" /></p>
<pre><code>## Warning: Removed 29 rows containing missing values (geom_path).</code></pre>
<p><img src="/blog/2019-08-17-transformed-exponentially-smoothed-power-and-other-techniques_files/figure-html/smoothing-3.svg" width="393.6" /></p>
<p><em>Disclaimer:</em><br />
<em>I’m not a physiologist and I’m not affiliated with any company. And yes I wrote all of this shit just out of pure interest.</em></p>
</div>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-Coggan2012">
<p>Allen, Hunter, and Andrew R. Coggan. 2012. <em>Training and Racing with a Power Meter: 2nd Edition</em>. 2nd ed. Velopress.</p>
</div>
<div id="ref-Brown">
<p>Brown, David. n.d. “SmO2 Weighted Average Power.” Accessed August 20, 2019. <a href="http://impactinformatics.com/SmO2WAP/SmO2WeightedAveragePower.html">http://impactinformatics.com/SmO2WAP/SmO2WeightedAveragePower.html</a>.</p>
</div>
<div id="ref-Coggan2003">
<p>Coggan, Andrew R. 2003. “Training and Racing Using a Power Meter: An Introduction.”</p>
</div>
<div id="ref-Coggan2006">
<p>———. 2006. “Making Sense Out of Apparent Chaos: Analyzing on the Bike Power Data.”</p>
</div>
<div id="ref-Endler2016">
<p>Endler, Stefan, Christian Secker, and Jörg Bügner. 2016. “What Is the Best Fitting Function? Evaluation of Lactate Curves with Common Methods from the Literature.” In <em>Proceedings of the 10th International Symposium on Computer Science in Sports (Iscss)</em>, 185–92. Springer International Publishing.</p>
</div>
<div id="ref-Faude2009">
<p>Faude, Oliver, Wilfried Kindermann, and Tim Meyer. 2009. “Lactate Threshold Concepts.” <em>Sports Medicine</em> 39 (6).</p>
</div>
<div id="ref-Lactate2017">
<p>“Lactate Threshold.” 2017. Sports Resource Group, Inc. <a href="http://www.lactate.com/lactate_threshold.html">http://www.lactate.com/lactate_threshold.html</a>.</p>
</div>
<div id="ref-Lactate2019">
<p>“Lactate Threshold.” 2019. Wikipedia, The Free Encyclopedia. <a href="https://en.wikipedia.org/wiki/Lactate_threshold">https://en.wikipedia.org/wiki/Lactate_threshold</a>.</p>
</div>
<div id="ref-Strava">
<p>“Power Analysis Features for Summit.” n.d. Strava. Accessed August 20, 2019. <a href="https://blog.strava.com/summit-power-analysis/">https://blog.strava.com/summit-power-analysis/</a>.</p>
</div>
<div id="ref-Skiba2008">
<p>Skiba, Philip F. 2008. “Analysis of Power Output and Training Stress in Cyclists: Development of the Bikescore Algorithm.”</p>
</div>
<div id="ref-Thorbj2018">
<p>Thorbjørnsen, Steen. 2018. <em>Videregående Sandsynlighedsteori</em>. 3rd ed. Aarhus Universitetsforlag.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Data measured using Lactate Analyzer and a Wattbike, accuracy +/- 2%.<a href="#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>
